name: Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 00:00 自动同步
    - cron: '0 0 * * *'
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 当前仓库
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.UPSTREAM_TOKEN }}

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/kimwang1978/collect-tv-txt.git

      - name: 拉取上游仓库更新
        run: |
          git fetch upstream

      - name: 合并到当前分支（如 main）
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge upstream/main
          git push origin main
